apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-smtp
  namespace: monitoring
type: Opaque
data:
  # echo -n 'user@example.com' | base64 -> dXNlckBleGFtcGxlLmNvbQ==
  user: dXNlckBleGFtcGxlLmNvbQ==
  # echo -n 'password-smtp-anda' | base64 -> cGFzc3dvcmQtc210cC1hbmRh
  password: cGFzc3dvcmQtc210cC1hbmRh