alertmanager:
  config:
    global:
      resolve_timeout: 5m
      # Referensi ke secret untuk kredensial SMTP
      smtp_from: "qahananfarizta@gmail.com" # Ganti dengan email pengirim Anda
      smtp_smarthost: "smtp.gmail.com:587" # Ganti dengan host SMTP Anda
      smtp_auth_username:
        name: alertmanager-smtp
        key: user
      smtp_auth_password:
        name: alertmanager-smtp
        key: password

    route:
      group_by: ["alertname", "namespace", "severity"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: "email-receiver"

    receivers:
      - name: "email-receiver"
        email_configs:
          - to: "hananfariztaa@gmail.com" # Ganti dengan email penerima
            send_resolved: true

# Konfigurasi Grafana
grafana:
  adminPassword: "prom-operator" # Ganti dengan password yang lebih aman, atau gunakan secret

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.devops.com # Ganti dengan domain Anda
    path: /

# Aktifkan service monitors untuk Trivy Operator
prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        release: trivy-operator
    serviceMonitorNamespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: security
