apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

# Definisikan nama dan tag image yang akan dipatch
images:
- name: hello-app-image
  newName: devopsappacr.azurecr.io/hello-app # Ganti dengan nama ACR Anda
  newTag: latest # Tag ini akan diganti oleh CI/CD